Route115_West_MapScripts::
	.byte 0

Route115_West_EventScript_LightHouseApprentice::
	msgbox Route115_West_Text_LightHouseApprentice, MSGBOX_NPC
	end

Route115_West_Text_LightHouseApprentice::
	.string "Oh hey! Must be one of those trainers\n"
	.string "training on our little peninsula.\p"
	.string "You won't find any challengers in this\n"
	.string "lighthouse, but you will find my master.\p"
	.string "He's teaching me how to look after the\n"
	.string "place.$"
