Route104_West_MapScripts::
	.byte 0

Route104_West_EventScript_Sign::
	msgbox Route104_West_Text_Sign, MSGBOX_SIGN
	end

Route104_West_Text_Sign:
	.string "Remember to pay attention to your\n"
	.string "surroundings.\p"
	.string "Secret passages are often hidden, but\n"
	.string "there's always a clue.\p"
	.string "Like missing shadows behind a tree or\n"
	.string "misplaced rubble on the floor.$"
